---
# Developed by TheAz928
#Config for WelcomeTitle

title: Hello {player}!

# Follow me on Twitter @TheAz928 , Thanks!
# Keep an eye on latest updates! Github.com\iSoftMC\WelcomeMessage
# or this link Githib.com/TheAz928/WelcomeMessage
...
